rules:
  bugs:
    inconsistent-args:
      level: ignore
  idiomatic:
    no-defined-entrypoint:
      level: ignore
    use-contains:
      level: ignore
    use-if:
      level: ignore
  style:
    avoid-get-and-list-prefix:
      level: ignore
    external-reference:
      level: ignore
    line-length:
      level: ignore
    no-whitespace-comment:
      level: ignore
    opa-fmt:
      level: ignore
    prefer-some-in-iteration:
      level: ignore
    prefer-snake-case:
      # 13 violations in the repo seems easy to fix
      level: ignore
    todo-comment:
      level: ignore
    unconditional-assignment:
      level: ignore
  imports:
    use-rego-v1:
      level: ignore
