rules:
  idiomatic:
    directory-package-mismatch:
      level: ignore
    no-defined-entrypoint:
      level: ignore
    use-contains:
      level: ignore
    use-if:
      level: ignore
  imports:
    use-rego-v1:
      level: ignore
  style:
    line-length:
      # if any single word on a line exceeds this length, ignore it
      non-breakable-word-threshold: 30
